# Generated by Django 5.2.6 on 2025-09-14 09:33

import core.utils
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('content', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Descriptive title for the ad', max_length=255, verbose_name='Title')),
                ('slug', models.SlugField(blank=True, help_text='URL-friendly version of the title', unique=True, verbose_name='Slug')),
                ('description', models.TextField(help_text='Detailed description of the item/service', verbose_name='Description')),
                ('price', models.CharField(blank=True, help_text='Price information (flexible text field)', max_length=100, verbose_name='Price')),
                ('contact_phone', models.CharField(help_text='Phone number for contact', max_length=20, verbose_name='Contact Phone')),
                ('contact_email', models.EmailField(help_text='Email address for contact', max_length=254, verbose_name='Contact Email')),
                ('plan', models.CharField(choices=[('free', 'Free Plan'), ('featured', 'Featured Plan')], default='free', max_length=10, verbose_name='Plan')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('expired', 'Expired')], default='pending', max_length=10, verbose_name='Status')),
                ('view_count', models.PositiveIntegerField(default=0, help_text='Number of times this ad was viewed', verbose_name='View Count')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expires_at', models.DateTimeField(help_text='When this ad expires', verbose_name='Expires At')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='Approved At')),
                ('admin_notes', models.TextField(blank=True, help_text='Internal notes for administrators', verbose_name='Admin Notes')),
                ('rejection_reason', models.TextField(blank=True, help_text='Reason for rejection (shown to user)', verbose_name='Rejection Reason')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_ads', to=settings.AUTH_USER_MODEL, verbose_name='Approved By')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ads', to='content.category', verbose_name='Category')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ads', to='content.city', verbose_name='City')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ads', to='content.state', verbose_name='State')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ads', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Ad',
                'verbose_name_plural': 'Ads',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AdImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Image file', upload_to=core.utils.generate_unique_filename, verbose_name='Image')),
                ('caption', models.CharField(blank=True, help_text='Optional caption for the image', max_length=255, verbose_name='Caption')),
                ('is_primary', models.BooleanField(default=False, help_text='Whether this is the main image for the ad', verbose_name='Is Primary')),
                ('sort_order', models.PositiveIntegerField(default=0, help_text='Order for displaying images', verbose_name='Sort Order')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='ads.ad', verbose_name='Ad')),
            ],
            options={
                'verbose_name': 'Ad Image',
                'verbose_name_plural': 'Ad Images',
                'ordering': ['sort_order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='AdView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(verbose_name='IP Address')),
                ('user_agent', models.TextField(help_text='Browser user agent string', verbose_name='User Agent')),
                ('viewed_at', models.DateTimeField(auto_now_add=True)),
                ('ad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detailed_views', to='ads.ad', verbose_name='Ad')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ad_views', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Ad View',
                'verbose_name_plural': 'Ad Views',
            },
        ),
        migrations.AddIndex(
            model_name='ad',
            index=models.Index(fields=['status', '-created_at'], name='ads_ad_status_df5568_idx'),
        ),
        migrations.AddIndex(
            model_name='ad',
            index=models.Index(fields=['category', 'state', 'status'], name='ads_ad_categor_39c431_idx'),
        ),
        migrations.AddIndex(
            model_name='ad',
            index=models.Index(fields=['city', 'status', '-created_at'], name='ads_ad_city_id_1801b1_idx'),
        ),
        migrations.AddIndex(
            model_name='ad',
            index=models.Index(fields=['user', '-created_at'], name='ads_ad_user_id_2a5cfb_idx'),
        ),
        migrations.AddIndex(
            model_name='ad',
            index=models.Index(fields=['plan', 'status'], name='ads_ad_plan_9fb3c1_idx'),
        ),
        migrations.AddIndex(
            model_name='ad',
            index=models.Index(fields=['expires_at'], name='ads_ad_expires_df7706_idx'),
        ),
        migrations.AddIndex(
            model_name='adimage',
            index=models.Index(fields=['ad', 'is_primary'], name='ads_adimage_ad_id_84a684_idx'),
        ),
        migrations.AddIndex(
            model_name='adimage',
            index=models.Index(fields=['ad', 'sort_order'], name='ads_adimage_ad_id_30a8a5_idx'),
        ),
        migrations.AddIndex(
            model_name='adview',
            index=models.Index(fields=['ad', '-viewed_at'], name='ads_adview_ad_id_387e29_idx'),
        ),
        migrations.AddIndex(
            model_name='adview',
            index=models.Index(fields=['user', '-viewed_at'], name='ads_adview_user_id_df77bc_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='adview',
            unique_together={('ad', 'ip_address', 'user_agent')},
        ),
    ]
