# Generated by Django 5.2.6 on 2025-09-21 09:21

import core.utils
import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0001_initial'),
        ('content', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(verbose_name='IP Address')),
                ('contact_type', models.CharField(choices=[('phone', 'Phone Number'), ('email', 'Email Address'), ('both', 'Both Phone and Email')], max_length=20, verbose_name='Contact Type')),
                ('viewed_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Ad Contact View',
                'verbose_name_plural': 'Ad Contact Views',
            },
        ),
        migrations.CreateModel(
            name='AdFavorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Ad Favorite',
                'verbose_name_plural': 'Ad Favorites',
            },
        ),
        migrations.CreateModel(
            name='AdReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('spam', 'Spam'), ('inappropriate', 'Inappropriate Content'), ('fraud', 'Fraudulent/Scam'), ('duplicate', 'Duplicate Posting'), ('wrong_category', 'Wrong Category'), ('other', 'Other')], max_length=20, verbose_name='Reason')),
                ('description', models.TextField(help_text='Additional details about the report', verbose_name='Description')),
                ('is_reviewed', models.BooleanField(default=False, verbose_name='Is Reviewed')),
                ('admin_notes', models.TextField(blank=True, verbose_name='Admin Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='Reviewed At')),
            ],
            options={
                'verbose_name': 'Ad Report',
                'verbose_name_plural': 'Ad Reports',
            },
        ),
        migrations.AlterUniqueTogether(
            name='adview',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='ad',
            name='condition',
            field=models.CharField(choices=[('new', 'New'), ('like_new', 'Like New'), ('good', 'Good'), ('fair', 'Fair'), ('poor', 'Poor'), ('not_applicable', 'Not Applicable')], default='not_applicable', help_text='Condition of the item', max_length=20, verbose_name='Condition'),
        ),
        migrations.AddField(
            model_name='ad',
            name='contact_count',
            field=models.PositiveIntegerField(default=0, help_text='Number of times contact info was viewed', verbose_name='Contact Count'),
        ),
        migrations.AddField(
            model_name='ad',
            name='favorite_count',
            field=models.PositiveIntegerField(default=0, help_text='Number of users who favorited this ad', verbose_name='Favorite Count'),
        ),
        migrations.AddField(
            model_name='ad',
            name='featured_expires_at',
            field=models.DateTimeField(blank=True, help_text='When featured status expires', null=True, verbose_name='Featured Expires At'),
        ),
        migrations.AddField(
            model_name='ad',
            name='featured_payment_id',
            field=models.CharField(blank=True, help_text='Payment transaction ID for featured ads', max_length=100, verbose_name='Payment ID'),
        ),
        migrations.AddField(
            model_name='ad',
            name='hide_phone',
            field=models.BooleanField(default=False, help_text='Hide phone number from public view', verbose_name='Hide Phone Number'),
        ),
        migrations.AddField(
            model_name='ad',
            name='keywords',
            field=models.CharField(blank=True, help_text='Comma-separated keywords for better search', max_length=500, verbose_name='Keywords'),
        ),
        migrations.AddField(
            model_name='ad',
            name='price_type',
            field=models.CharField(choices=[('fixed', 'Fixed Price'), ('negotiable', 'Negotiable'), ('contact', 'Contact for Price'), ('free', 'Free'), ('swap', 'Swap/Trade')], default='fixed', help_text='Type of pricing', max_length=20, verbose_name='Price Type'),
        ),
        migrations.AddField(
            model_name='ad',
            name='unique_view_count',
            field=models.PositiveIntegerField(default=0, help_text='Number of unique users who viewed', verbose_name='Unique View Count'),
        ),
        migrations.AddField(
            model_name='adimage',
            name='file_size',
            field=models.PositiveIntegerField(blank=True, help_text='File size in bytes', null=True, verbose_name='File Size'),
        ),
        migrations.AddField(
            model_name='adimage',
            name='height',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Height'),
        ),
        migrations.AddField(
            model_name='adimage',
            name='width',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Width'),
        ),
        migrations.AddField(
            model_name='adview',
            name='device_type',
            field=models.CharField(choices=[('desktop', 'Desktop'), ('mobile', 'Mobile'), ('tablet', 'Tablet'), ('unknown', 'Unknown')], default='unknown', max_length=20, verbose_name='Device Type'),
        ),
        migrations.AddField(
            model_name='adview',
            name='referrer',
            field=models.URLField(blank=True, help_text='Page that referred to this ad', verbose_name='Referrer'),
        ),
        migrations.AddField(
            model_name='adview',
            name='session_id',
            field=models.CharField(blank=True, help_text='Anonymous session identifier', max_length=50, verbose_name='Session ID'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='contact_email',
            field=models.EmailField(blank=True, help_text='Email for contact (optional, uses user email if blank)', max_length=254, verbose_name='Contact Email'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='contact_phone',
            field=models.CharField(blank=True, help_text='Phone number for contact (optional)', max_length=20, verbose_name='Contact Phone'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='plan',
            field=models.CharField(choices=[('free', 'Free Plan'), ('featured', 'Featured Plan - $9.99')], default='free', help_text='Ad plan type', max_length=20, verbose_name='Plan'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Price in USD (leave blank for contact for price)', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('expired', 'Expired'), ('sold', 'Sold/Closed')], default='draft', help_text='Current status of the ad', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='view_count',
            field=models.PositiveIntegerField(default=0, help_text='Number of times ad has been viewed', verbose_name='View Count'),
        ),
        migrations.AlterField(
            model_name='adimage',
            name='image',
            field=models.ImageField(help_text='Image file (max 5MB)', upload_to=core.utils.generate_unique_filename, verbose_name='Image'),
        ),
        migrations.AlterUniqueTogether(
            name='adview',
            unique_together={('ad', 'session_id')},
        ),
        migrations.AddIndex(
            model_name='ad',
            index=models.Index(fields=['featured_expires_at'], name='ads_ad_feature_bf2595_idx'),
        ),
        migrations.AddIndex(
            model_name='ad',
            index=models.Index(fields=['slug'], name='ads_ad_slug_35a381_idx'),
        ),
        migrations.AddIndex(
            model_name='adview',
            index=models.Index(fields=['ip_address', '-viewed_at'], name='ads_adview_ip_addr_a91647_idx'),
        ),
        migrations.AddField(
            model_name='adcontact',
            name='ad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_views', to='ads.ad', verbose_name='Ad'),
        ),
        migrations.AddField(
            model_name='adcontact',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contact_views', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AddField(
            model_name='adfavorite',
            name='ad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='ads.ad', verbose_name='Ad'),
        ),
        migrations.AddField(
            model_name='adfavorite',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_ads', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AddField(
            model_name='adreport',
            name='ad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='ads.ad', verbose_name='Ad'),
        ),
        migrations.AddField(
            model_name='adreport',
            name='reported_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ad_reports', to=settings.AUTH_USER_MODEL, verbose_name='Reported By'),
        ),
        migrations.AddField(
            model_name='adreport',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_reports', to=settings.AUTH_USER_MODEL, verbose_name='Reviewed By'),
        ),
        migrations.AddIndex(
            model_name='adcontact',
            index=models.Index(fields=['ad', '-viewed_at'], name='ads_adconta_ad_id_1e8772_idx'),
        ),
        migrations.AddIndex(
            model_name='adcontact',
            index=models.Index(fields=['user', '-viewed_at'], name='ads_adconta_user_id_25af74_idx'),
        ),
        migrations.AddIndex(
            model_name='adfavorite',
            index=models.Index(fields=['user', '-created_at'], name='ads_adfavor_user_id_d15df4_idx'),
        ),
        migrations.AddIndex(
            model_name='adfavorite',
            index=models.Index(fields=['ad', '-created_at'], name='ads_adfavor_ad_id_5a44d8_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='adfavorite',
            unique_together={('ad', 'user')},
        ),
        migrations.AddIndex(
            model_name='adreport',
            index=models.Index(fields=['ad', '-created_at'], name='ads_adrepor_ad_id_549249_idx'),
        ),
        migrations.AddIndex(
            model_name='adreport',
            index=models.Index(fields=['is_reviewed', '-created_at'], name='ads_adrepor_is_revi_fc0649_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='adreport',
            unique_together={('ad', 'reported_by')},
        ),
    ]
