# Generated by Django 5.2.6 on 2025-10-01 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0002_adcontact_adfavorite_adreport_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('expired', 'Expired'), ('sold', 'Sold/Closed')], default='pending', help_text='Current status of the ad', max_length=20, verbose_name='Status'),
        ),
    ]
