# Generated by Django 5.2.6 on 2025-09-20 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_verification_token_created_and_more'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='user',
            name='accounts_us_email_v_054104_idx',
        ),
        migrations.RemoveField(
            model_name='user',
            name='verification_token_created',
        ),
        migrations.AddField(
            model_name='user',
            name='email_verification_expires',
            field=models.DateTimeField(blank=True, help_text='When the email verification code expires', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='password_reset_expires',
            field=models.DateTimeField(blank=True, help_text='When the password reset code expires', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='password_reset_token',
            field=models.CharField(blank=True, help_text='6-digit code for password reset', max_length=6),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(max_length=150, verbose_name='last name'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['email_verification_token'], name='accounts_us_email_v_bf9c13_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['password_reset_token'], name='accounts_us_passwor_296d11_idx'),
        ),
    ]
