# Generated by Django 5.2.6 on 2025-09-27 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_user_accounts_us_email_v_054104_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_notifications',
            field=models.BooleanField(default=True, help_text='Receive email notifications for important updates', verbose_name='Email Notifications'),
        ),
        migrations.AddField(
            model_name='user',
            name='show_email',
            field=models.BooleanField(default=False, help_text='Allow other users to see your email address on ads', verbose_name='Show Email Publicly'),
        ),
        migrations.AddField(
            model_name='user',
            name='show_phone',
            field=models.BooleanField(default=True, help_text='Allow other users to see your phone number on ads', verbose_name='Show Phone Publicly'),
        ),
    ]
