# Generated by Django 5.2.6 on 2025-10-14 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_email_notifications_user_show_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_message_notifications',
            field=models.BooleanField(default=True, help_text='Receive email notifications for new messages and conversations', verbose_name='Email Message Notifications'),
        ),
    ]
