# Generated by Django 5.2.6 on 2025-09-27 15:55

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('content', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='Classified Ads', max_length=100, verbose_name='Site Name')),
                ('contact_email', models.EmailField(max_length=254, verbose_name='Contact Email')),
                ('support_phone', models.CharField(blank=True, max_length=20, verbose_name='Support Phone')),
                ('ad_approval_required', models.BooleanField(default=True, help_text='Require admin approval for new ads', verbose_name='Ad Approval Required')),
                ('featured_ad_price', models.DecimalField(decimal_places=2, default=9.99, max_digits=10, verbose_name='Featured Ad Price')),
                ('max_images_per_ad', models.PositiveIntegerField(default=10, verbose_name='Max Images Per Ad')),
                ('ad_expiration_days', models.PositiveIntegerField(default=90, help_text='Days after which ads expire', verbose_name='Ad Expiration Days')),
                ('user_registration_enabled', models.BooleanField(default=True, verbose_name='User Registration Enabled')),
                ('email_verification_required', models.BooleanField(default=True, verbose_name='Email Verification Required')),
                ('max_ads_per_user', models.PositiveIntegerField(default=50, help_text='Maximum number of active ads per user', verbose_name='Max Ads Per User')),
                ('admin_email_notifications', models.BooleanField(default=True, verbose_name='Admin Email Notifications')),
                ('user_email_notifications', models.BooleanField(default=True, verbose_name='User Email Notifications')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_settings', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
            ],
            options={
                'verbose_name': 'Admin Settings',
                'verbose_name_plural': 'Admin Settings',
            },
        ),
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('banner_type', models.CharField(choices=[('image', 'Image Banner'), ('html', 'HTML Banner'), ('text', 'Text Banner')], default='image', max_length=20, verbose_name='Banner Type')),
                ('image', models.ImageField(blank=True, null=True, upload_to='banners/', verbose_name='Banner Image')),
                ('html_content', models.TextField(blank=True, help_text='For HTML banners', verbose_name='HTML Content')),
                ('text_content', models.TextField(blank=True, help_text='For text banners', verbose_name='Text Content')),
                ('position', models.CharField(choices=[('header', 'Header'), ('sidebar', 'Sidebar'), ('footer', 'Footer'), ('between_ads', 'Between Ads'), ('category_page', 'Category Page'), ('ad_detail', 'Ad Detail Page')], max_length=20, verbose_name='Position')),
                ('click_url', models.URLField(blank=True, verbose_name='Click URL')),
                ('open_new_tab', models.BooleanField(default=True, verbose_name='Open in New Tab')),
                ('impressions', models.PositiveIntegerField(default=0, verbose_name='Impressions')),
                ('clicks', models.PositiveIntegerField(default=0, verbose_name='Clicks')),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Start Date')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name='End Date')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('priority', models.PositiveIntegerField(default=0, help_text='Higher numbers have higher priority', verbose_name='Priority')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_banners', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('target_categories', models.ManyToManyField(blank=True, help_text='Leave empty to show in all categories', to='content.category', verbose_name='Target Categories')),
                ('target_states', models.ManyToManyField(blank=True, help_text='Leave empty to show in all states', to='content.state', verbose_name='Target States')),
            ],
            options={
                'verbose_name': 'Banner',
                'verbose_name_plural': 'Banners',
                'ordering': ['-priority', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BannerClick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField()),
                ('referrer', models.URLField(blank=True)),
                ('clicked_at', models.DateTimeField(auto_now_add=True)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('banner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='click_logs', to='administrator.banner')),
            ],
            options={
                'verbose_name': 'Banner Click',
                'verbose_name_plural': 'Banner Clicks',
            },
        ),
        migrations.CreateModel(
            name='BannerImpression',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField()),
                ('page_url', models.URLField()),
                ('viewed_at', models.DateTimeField(auto_now_add=True)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('banner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='impression_logs', to='administrator.banner')),
            ],
            options={
                'verbose_name': 'Banner Impression',
                'verbose_name_plural': 'Banner Impressions',
            },
        ),
        migrations.AddIndex(
            model_name='banner',
            index=models.Index(fields=['position', 'is_active'], name='administrat_positio_68b3c4_idx'),
        ),
        migrations.AddIndex(
            model_name='banner',
            index=models.Index(fields=['start_date', 'end_date'], name='administrat_start_d_f655b6_idx'),
        ),
        migrations.AddIndex(
            model_name='banner',
            index=models.Index(fields=['-priority'], name='administrat_priorit_34e48c_idx'),
        ),
        migrations.AddIndex(
            model_name='bannerclick',
            index=models.Index(fields=['banner', '-clicked_at'], name='administrat_banner__0ea10a_idx'),
        ),
        migrations.AddIndex(
            model_name='bannerclick',
            index=models.Index(fields=['-clicked_at'], name='administrat_clicked_228563_idx'),
        ),
        migrations.AddIndex(
            model_name='bannerimpression',
            index=models.Index(fields=['banner', '-viewed_at'], name='administrat_banner__d6280f_idx'),
        ),
        migrations.AddIndex(
            model_name='bannerimpression',
            index=models.Index(fields=['-viewed_at'], name='administrat_viewed__e68de7_idx'),
        ),
    ]
