# Generated by Django 5.2.6 on 2025-10-26 08:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='bannerclick',
            name='administrat_clicked_228563_idx',
        ),
        migrations.RemoveIndex(
            model_name='bannerimpression',
            name='administrat_viewed__e68de7_idx',
        ),
        migrations.AddField(
            model_name='bannerclick',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bannerimpression',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='bannerclick',
            name='city',
            field=models.CharField(blank=True, max_length=100, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='bannerclick',
            name='clicked_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Clicked At'),
        ),
        migrations.AlterField(
            model_name='bannerclick',
            name='country',
            field=models.CharField(blank=True, max_length=100, verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='bannerclick',
            name='ip_address',
            field=models.GenericIPAddressField(verbose_name='IP Address'),
        ),
        migrations.AlterField(
            model_name='bannerclick',
            name='referrer',
            field=models.URLField(blank=True, verbose_name='Referrer URL'),
        ),
        migrations.AlterField(
            model_name='bannerclick',
            name='state',
            field=models.CharField(blank=True, max_length=100, verbose_name='State'),
        ),
        migrations.AlterField(
            model_name='bannerclick',
            name='user_agent',
            field=models.TextField(blank=True, verbose_name='User Agent'),
        ),
        migrations.AlterField(
            model_name='bannerimpression',
            name='city',
            field=models.CharField(blank=True, max_length=100, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='bannerimpression',
            name='country',
            field=models.CharField(blank=True, max_length=100, verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='bannerimpression',
            name='ip_address',
            field=models.GenericIPAddressField(verbose_name='IP Address'),
        ),
        migrations.AlterField(
            model_name='bannerimpression',
            name='page_url',
            field=models.URLField(blank=True, verbose_name='Page URL'),
        ),
        migrations.AlterField(
            model_name='bannerimpression',
            name='state',
            field=models.CharField(blank=True, max_length=100, verbose_name='State'),
        ),
        migrations.AlterField(
            model_name='bannerimpression',
            name='user_agent',
            field=models.TextField(blank=True, verbose_name='User Agent'),
        ),
        migrations.AlterField(
            model_name='bannerimpression',
            name='viewed_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Viewed At'),
        ),
        migrations.AddIndex(
            model_name='bannerclick',
            index=models.Index(fields=['clicked_at'], name='administrat_clicked_f87637_idx'),
        ),
        migrations.AddIndex(
            model_name='bannerimpression',
            index=models.Index(fields=['viewed_at'], name='administrat_viewed__81e1f1_idx'),
        ),
    ]
