# Generated by Django 5.2.6 on 2025-10-29 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0002_remove_bannerclick_administrat_clicked_228563_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminsettings',
            name='allow_registration',
            field=models.BooleanField(default=True, help_text='Allow new users to register', verbose_name='Allow Registration'),
        ),
        migrations.AddField(
            model_name='adminsettings',
            name='auto_approve_ads',
            field=models.BooleanField(default=False, help_text='Automatically approve new ads without manual review', verbose_name='Auto Approve Ads'),
        ),
        migrations.AddField(
            model_name='adminsettings',
            name='featured_ad_duration_days',
            field=models.PositiveIntegerField(default=30, help_text='Days that featured ads remain active', verbose_name='Featured Ad Duration Days'),
        ),
        migrations.AddField(
            model_name='adminsettings',
            name='maintenance_message',
            field=models.TextField(blank=True, default='We are currently performing scheduled maintenance. Please check back soon.', verbose_name='Maintenance Message'),
        ),
        migrations.AddField(
            model_name='adminsettings',
            name='maintenance_mode',
            field=models.BooleanField(default=False, help_text='Enable maintenance mode to block non-admin users', verbose_name='Maintenance Mode'),
        ),
        migrations.AddField(
            model_name='adminsettings',
            name='require_email_verification',
            field=models.BooleanField(default=True, help_text='Force users to verify email before accessing features', verbose_name='Require Email Verification'),
        ),
        migrations.AlterField(
            model_name='adminsettings',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Contact Email'),
        ),
    ]
