# Generated by Django 5.2.6 on 2025-09-14 09:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Category name (e.g., Jobs, Real Estate)', max_length=100, unique=True, verbose_name='Category Name')),
                ('slug', models.SlugField(blank=True, help_text='URL-friendly version of the category name', unique=True, verbose_name='Slug')),
                ('icon', models.CharField(help_text='Icon for the category (emoji or CSS class)', max_length=50, verbose_name='Icon')),
                ('description', models.TextField(blank=True, help_text='Optional description of the category', verbose_name='Description')),
                ('sort_order', models.PositiveIntegerField(default=0, help_text='Order for displaying categories (lower numbers first)', verbose_name='Sort Order')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this category accepts new ads', verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ['sort_order', 'name'],
                'indexes': [models.Index(fields=['is_active', 'sort_order'], name='content_cat_is_acti_59b16c_idx'), models.Index(fields=['slug'], name='content_cat_slug_d6cc3e_idx')],
            },
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Full state name (e.g., Illinois)', max_length=100, unique=True, verbose_name='State Name')),
                ('code', models.CharField(help_text='2-letter state code (e.g., IL)', max_length=2, unique=True, verbose_name='State Code')),
                ('domain', models.CharField(help_text='Domain for this state (e.g., desiloginil.com)', max_length=255, unique=True, verbose_name='Domain')),
                ('logo', models.ImageField(help_text='Logo for this state', upload_to='states/logos/', verbose_name='State Logo')),
                ('favicon', models.ImageField(blank=True, help_text='Favicon for this state (optional)', null=True, upload_to='states/favicons/', verbose_name='Favicon')),
                ('meta_title', models.CharField(help_text='SEO title for the state homepage', max_length=255, verbose_name='Meta Title')),
                ('meta_description', models.TextField(help_text='SEO description for the state homepage', verbose_name='Meta Description')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this state is active and accepting ads', verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'State',
                'verbose_name_plural': 'States',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['code'], name='content_sta_code_3d8f9a_idx'), models.Index(fields=['domain'], name='content_sta_domain_96efb5_idx'), models.Index(fields=['is_active'], name='content_sta_is_acti_2d33e9_idx')],
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='City name (e.g., Chicago)', max_length=100, verbose_name='City Name')),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, help_text='City latitude for mapping (optional)', max_digits=10, null=True, verbose_name='Latitude')),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, help_text='City longitude for mapping (optional)', max_digits=10, null=True, verbose_name='Longitude')),
                ('is_major', models.BooleanField(default=False, help_text='Whether this is a major city (appears first in lists)', verbose_name='Major City')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this city accepts ads', verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='content.state', verbose_name='State')),
            ],
            options={
                'verbose_name': 'City',
                'verbose_name_plural': 'Cities',
                'ordering': ['-is_major', 'name'],
                'indexes': [models.Index(fields=['state', 'is_major'], name='content_cit_state_i_358917_idx'), models.Index(fields=['state', 'is_active'], name='content_cit_state_i_790c19_idx')],
                'unique_together': {('name', 'state')},
            },
        ),
    ]
