# Generated by Django 5.2.6 on 2025-09-27 17:38

import core.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='photo',
            field=models.ImageField(blank=True, help_text='City photo/banner image for display', null=True, upload_to=core.utils.generate_unique_filename, verbose_name='City Photo'),
        ),
    ]
